# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aff7ec719fad75a76709ee8dd9da2797c1648ecd07e8c1e579ad729cfec7245c811d73293fd03f820b97125044d383947efc12d2002f32ff77a66865a224495

test:
  secret_key_base: 81ee4fd5d942a0c45e9bb687a4a158b9f95664927c0d0318678f487b9cbd5790e0c1b0a166f1df7b5cd12add799ae2b2b427b3d9e43f9f575198053e40989d89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
